
2014/11/05 16:43:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://ybugs.local/en
---
2014/11/06 16:47:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/06 16:59:18 [error] [exception.CException] exception 'CException' with message 'IssuesController cannot find the requested view "get_iisue".' in /Applications/AMPPS/www/ybugs.local/framework/web/CController.php:878
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(782): CController->renderPartial('get_iisue', Array, true)
#1 /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php(38): CController->render('get_iisue', Array)
#2 [internal function]: IssuesController->actionGetissue('1')
#3 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#4 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#5 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(282): CController->run('getissue')
#9 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('issues/getissue')
#10 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/en/issues/getissue/1
HTTP_REFERER=http://ybugs.local/en/issues/list/1
---
2014/11/06 18:50:58 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "CDbCommand.queryAll".' in /Applications/AMPPS/www/ybugs.local/framework/base/CComponent.php:130
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/protected/models/ext/ExtIssues.php(30): CComponent->__get('queryAll')
#1 /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php(36): ExtIssues->getIssue('3')
#2 [internal function]: IssuesController->actionGetissue('3')
#3 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#4 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#5 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(282): CController->run('getissue')
#9 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('issues/getissue')
#10 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/ru/issues/getissue/3
HTTP_REFERER=http://ybugs.local/ru/issues/list/2
---
2014/11/06 19:42:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "issue/getissue".' in /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('issue/getissue')
#1 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ru/issue/getissue/
HTTP_REFERER=http://ybugs.local/ru/issues/list/2
---
2014/11/06 19:42:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "issue/getissue".' in /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('issue/getissue')
#1 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ru/issue/getissue/3
HTTP_REFERER=http://ybugs.local/ru/issues/list/2
---
2014/11/07 14:32:13 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.user_id" is not defined.' in C:\OpenServer\domains\ybugs.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\auth\CWebUser.php(146): CComponent->__get('user_id')
#1 C:\OpenServer\domains\ybugs.local\protected\widgets\AsideMenu.php(10): CWebUser->__get('user_id')
#2 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(173): AsideMenu->run()
#3 C:\OpenServer\domains\ybugs.local\protected\views\layouts\main_layout.php(49): CBaseController->widget('application.wid...')
#4 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#5 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(784): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#7 C:\OpenServer\domains\ybugs.local\protected\controllers\MainController.php(14): CController->render('index', Array)
#8 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): MainController->actionIndex()
#9 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/index')
#14 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/en/main/index
HTTP_REFERER=http://ybugs.local/en/main/login
---
2014/11/07 14:32:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/07 15:16:07 [error] [exception.CException] exception 'CException' with message 'ProjectsController cannot find the requested view "main/index".' in C:\OpenServer\domains\ybugs.local\framework\web\CController.php:878
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(782): CController->renderPartial('main/index', Array, true)
#1 C:\OpenServer\domains\ybugs.local\protected\controllers\ProjectsController.php(24): CController->render('main/index', Array)
#2 C:\OpenServer\domains\ybugs.local\protected\controllers\ProjectsController.php(10): ProjectsController->actionList()
#3 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): ProjectsController->actionIndex()
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('index')
#8 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('projects/index')
#9 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/en/projects
HTTP_REFERER=http://ybugs.local/en/issues/getissue/7
---
2014/11/07 15:24:53 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:123
Stack trace:
#0 [internal function]: IssuesController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/issues/add
HTTP_REFERER=http://ybugs.local/en/issues/list/2
---
2014/11/07 15:26:19 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:123
Stack trace:
#0 [internal function]: IssuesController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/issues/add
HTTP_REFERER=http://ybugs.local/en/issues/list/2
---
2014/11/07 15:33:41 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:123
Stack trace:
#0 [internal function]: IssuesController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/issues/add
HTTP_REFERER=http://ybugs.local/en/issues/list/2
---
2014/11/07 15:33:45 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:123
Stack trace:
#0 [internal function]: IssuesController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add/2')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/issues/add/2
HTTP_REFERER=http://ybugs.local/en/issues/list/2
---
2014/11/08 22:52:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/08 22:52:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/08 23:15:29 [error] [exception.CHttpException.404] exception 'CHttpException' in /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php:123
Stack trace:
#0 [internal function]: IssuesController->actionAdd('__URL__')
#1 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(282): CController->run('add')
#7 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('issues/add/id/_...')
#8 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/issues/add/id/__URL__
HTTP_REFERER=http://ybugs.local/issues/add/id/1
---
2014/11/09 00:42:24 [error] [php] include(Translations.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (/Applications/AMPPS/www/ybugs.local/framework/YiiBase.php:427)
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/protected/models/forms/IssueForm.php(24): spl_autoload_call()
#1 /Applications/AMPPS/www/ybugs.local/framework/base/CModel.php(284): IssueForm->rules()
#2 /Applications/AMPPS/www/ybugs.local/framework/base/CModel.php(260): IssueForm->createValidators()
#3 /Applications/AMPPS/www/ybugs.local/framework/web/helpers/CHtml.php(2236): IssueForm->getValidators()
#4 /Applications/AMPPS/www/ybugs.local/framework/web/helpers/CHtml.php(1434): activeInputField()
#5 /Applications/AMPPS/www/ybugs.local/framework/web/widgets/CActiveForm.php(725): activeTextField()
#6 /Applications/AMPPS/www/ybugs.local/protected/views/issues/add.php(20): CActiveForm->textField()
#7 /Applications/AMPPS/www/ybugs.local/framework/web/CBaseController.php(126): require()
#8 /Applications/AMPPS/www/ybugs.local/framework/web/CBaseController.php(95): IssuesController->renderInternal()
#9 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(869): IssuesController->renderFile()
#10 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(782): IssuesController->renderPartial()
#11 /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php(109): IssuesController->render()
#12 unknown(0): IssuesController->actionAdd()
#13 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs()
#14 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#15 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(308): CInlineAction->runWithParams()
#16 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(286): IssuesController->runAction()
#17 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(265): IssuesController->runActionWithFilters()
#18 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(282): IssuesController->run()
#19 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController()
#20 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#21 /Applications/AMPPS/www/ybugs.local/index.php(13): CWebApplication->run()
REQUEST_URI=/issues/add/id/1
in /Applications/AMPPS/www/ybugs.local/protected/models/forms/IssueForm.php (24)
in /Applications/AMPPS/www/ybugs.local/protected/views/issues/add.php (20)
in /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php (109)
2014/11/09 00:44:33 [warning] [application] Failed to set unsafe attribute "title" of "IssueForm".
in /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php (63)
in /Applications/AMPPS/www/ybugs.local/index.php (13)
2014/11/09 00:44:36 [warning] [application] Failed to set unsafe attribute "title" of "IssueForm".
in /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php (63)
in /Applications/AMPPS/www/ybugs.local/index.php (13)
2014/11/09 00:44:39 [warning] [application] Failed to set unsafe attribute "title" of "IssueForm".
in /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php (63)
in /Applications/AMPPS/www/ybugs.local/index.php (13)
2014/11/09 19:00:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/09 20:24:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/09 20:33:02 [error] [php] Invalid argument supplied for foreach() (/Applications/AMPPS/www/ybugs.local/framework/web/helpers/CHtml.php:2325)
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/protected/views/issues/add.php(28): CActiveForm->dropDownList()
#1 /Applications/AMPPS/www/ybugs.local/framework/web/CBaseController.php(126): require()
#2 /Applications/AMPPS/www/ybugs.local/framework/web/CBaseController.php(95): IssuesController->renderInternal()
#3 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(869): IssuesController->renderFile()
#4 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(782): IssuesController->renderPartial()
#5 /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php(109): IssuesController->render()
#6 unknown(0): IssuesController->actionAdd()
#7 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs()
#8 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#9 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(308): CInlineAction->runWithParams()
#10 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(286): IssuesController->runAction()
#11 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(265): IssuesController->runActionWithFilters()
#12 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(282): IssuesController->run()
#13 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController()
#14 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /Applications/AMPPS/www/ybugs.local/index.php(13): CWebApplication->run()
REQUEST_URI=/issues/add/id/1
in /Applications/AMPPS/www/ybugs.local/protected/views/issues/add.php (28)
in /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php (109)
in /Applications/AMPPS/www/ybugs.local/index.php (13)
2014/11/09 20:34:26 [error] [php] Invalid argument supplied for foreach() (/Applications/AMPPS/www/ybugs.local/framework/web/helpers/CHtml.php:2325)
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/protected/views/issues/add.php(28): CActiveForm->dropDownList()
#1 /Applications/AMPPS/www/ybugs.local/framework/web/CBaseController.php(126): require()
#2 /Applications/AMPPS/www/ybugs.local/framework/web/CBaseController.php(95): IssuesController->renderInternal()
#3 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(869): IssuesController->renderFile()
#4 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(782): IssuesController->renderPartial()
#5 /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php(109): IssuesController->render()
#6 unknown(0): IssuesController->actionAdd()
#7 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs()
#8 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#9 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(308): CInlineAction->runWithParams()
#10 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(286): IssuesController->runAction()
#11 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(265): IssuesController->runActionWithFilters()
#12 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(282): IssuesController->run()
#13 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController()
#14 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /Applications/AMPPS/www/ybugs.local/index.php(13): CWebApplication->run()
REQUEST_URI=/issues/add/id/1
in /Applications/AMPPS/www/ybugs.local/protected/views/issues/add.php (28)
in /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php (109)
in /Applications/AMPPS/www/ybugs.local/index.php (13)
2014/11/09 22:16:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/09 22:44:45 [warning] [application] Failed to set unsafe attribute "files" of "Issues".
in /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php (69)
in /Applications/AMPPS/www/ybugs.local/index.php (13)
2014/11/09 22:44:45 [warning] [application] Failed to set unsafe attribute "priority" of "Issues".
in /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php (69)
in /Applications/AMPPS/www/ybugs.local/index.php (13)
2014/11/10 14:12:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/10 14:15:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/10 14:22:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/10 15:01:08 [warning] [application] Failed to set unsafe attribute "files" of "IssueForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php (63)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/10 15:03:14 [warning] [application] Failed to set unsafe attribute "files" of "IssueForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php (63)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/10 15:04:05 [warning] [application] Failed to set unsafe attribute "files" of "IssueForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php (63)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/10 15:04:05 [warning] [application] Failed to set unsafe attribute "files" of "Issues".
in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php (69)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/10 15:04:05 [warning] [application] Failed to set unsafe attribute "priority" of "Issues".
in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php (69)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/10 15:05:26 [warning] [application] Failed to set unsafe attribute "files" of "IssueForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php (63)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/10 15:05:26 [warning] [application] Failed to set unsafe attribute "files" of "Issues".
in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php (69)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/10 15:05:26 [warning] [application] Failed to set unsafe attribute "priority" of "Issues".
in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php (69)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/10 15:08:57 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:106
Stack trace:
#0 [internal function]: IssuesController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/lt/issues/add/
HTTP_REFERER=http://ybugs.local/issues/add/id/2
---
2014/11/10 15:09:16 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:106
Stack trace:
#0 [internal function]: IssuesController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/lt/issues/add/
---
2014/11/10 15:09:19 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:106
Stack trace:
#0 [internal function]: IssuesController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/lt/issues/add/
---
2014/11/10 15:16:49 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:106
Stack trace:
#0 [internal function]: IssuesController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/lt/issues/add/
HTTP_REFERER=http://ybugs.local/issues/add/id/2
---
2014/11/10 15:27:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://ybugs.local/en/issues/list/1
---
2014/11/10 15:27:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://ybugs.local/issues/add/id/2
---
2014/11/10 15:28:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/10 15:28:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/10 16:41:44 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:106
Stack trace:
#0 [internal function]: IssuesController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add/9')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/issues/add/9
HTTP_REFERER=http://ybugs.local/en/issues/getissue/9
---
2014/11/10 16:41:44 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:106
Stack trace:
#0 [internal function]: IssuesController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add/9')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/issues/add/9
HTTP_REFERER=http://ybugs.local/en/issues/getissue/9
---
2014/11/10 16:42:46 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\ResolutionsController.php:48
Stack trace:
#0 [internal function]: ResolutionsController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(ResolutionsController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ResolutionsController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('resolutions/add...')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/resolutions/add/9
HTTP_REFERER=http://ybugs.local/en/issues/getissue/9
---
2014/11/10 17:07:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Wron resolition' in C:\OpenServer\domains\ybugs.local\protected\controllers\ResolutionsController.php:84
Stack trace:
#0 [internal function]: ResolutionsController->actionAdd(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(ResolutionsController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ResolutionsController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('resolutions/add...')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/resolutions/add/9
---
2014/11/10 17:45:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Wron resolition' in C:\OpenServer\domains\ybugs.local\protected\controllers\ResolutionsController.php:85
Stack trace:
#0 [internal function]: ResolutionsController->actionAdd('9')
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(ResolutionsController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ResolutionsController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('resolutions/add')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/en/resolutions/add/9
---
2014/11/10 18:00:43 [error] [exception.CException] exception 'CException' with message 'CActiveForm has an extra endWidget() call in its view.' in C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php:210
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\protected\views\resolutions\add.php(28): CBaseController->endWidget()
#1 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(782): CController->renderPartial('add', Array, true)
#5 C:\OpenServer\domains\ybugs.local\protected\controllers\ResolutionsController.php(80): CController->render('add', Array)
#6 [internal function]: ResolutionsController->actionAdd('9')
#7 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(ResolutionsController), Array)
#8 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ResolutionsController), Object(ReflectionMethod), Array)
#9 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#13 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('resolutions/add')
#14 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/en/resolutions/add/9
---
2014/11/10 18:06:47 [error] [php] Creating default object from empty value (C:\OpenServer\domains\ybugs.local\protected\controllers\ResolutionsController.php:70)
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): ResolutionsController->runAction()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): ResolutionsController->runActionWithFilters()
#4 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): ResolutionsController->run()
#5 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#6 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#7 C:\OpenServer\domains\ybugs.local\index.php(13): CWebApplication->run()
REQUEST_URI=/en/resolutions/add/9
in C:\OpenServer\domains\ybugs.local\protected\controllers\ResolutionsController.php (70)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/10 18:50:35 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:106
Stack trace:
#0 [internal function]: IssuesController->actionAdd('')
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add/id')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/issues/add/id/
HTTP_REFERER=http://ybugs.local/en/issues/list/9
---
2014/11/10 22:41:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/11 00:35:13 [error] [php] include(Translations.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\OpenServer\domains\ybugs.local\framework\YiiBase.php:427)
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\protected\views\users\list.php(6): spl_autoload_call()
#1 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(126): require()
#2 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(95): UsersController->renderInternal()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(869): UsersController->renderFile()
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(782): UsersController->renderPartial()
#5 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(30): UsersController->render()
#6 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(10): UsersController->actionList()
#7 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#8 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): UsersController->runAction()
#10 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): UsersController->runActionWithFilters()
#11 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): UsersController->run()
#12 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\ybugs.local\index.php(13): CWebApplication->run()
REQUEST_URI=/en/users
in C:\OpenServer\domains\ybugs.local\protected\views\users\list.php (6)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (30)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (10)
2014/11/11 00:35:44 [error] [php] include(Translations.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\OpenServer\domains\ybugs.local\framework\YiiBase.php:427)
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\protected\views\users\list.php(6): spl_autoload_call()
#1 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(126): require()
#2 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(95): UsersController->renderInternal()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(869): UsersController->renderFile()
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(782): UsersController->renderPartial()
#5 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(30): UsersController->render()
#6 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(10): UsersController->actionList()
#7 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#8 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): UsersController->runAction()
#10 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): UsersController->runActionWithFilters()
#11 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): UsersController->run()
#12 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\ybugs.local\index.php(13): CWebApplication->run()
REQUEST_URI=/en/users
in C:\OpenServer\domains\ybugs.local\protected\views\users\list.php (6)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (30)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (10)
2014/11/11 00:36:18 [error] [php] include(Translations.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\OpenServer\domains\ybugs.local\framework\YiiBase.php:427)
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\protected\views\users\list.php(6): spl_autoload_call()
#1 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(126): require()
#2 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(95): UsersController->renderInternal()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(869): UsersController->renderFile()
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(782): UsersController->renderPartial()
#5 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(30): UsersController->render()
#6 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(10): UsersController->actionList()
#7 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#8 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): UsersController->runAction()
#10 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): UsersController->runActionWithFilters()
#11 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): UsersController->run()
#12 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\ybugs.local\index.php(13): CWebApplication->run()
REQUEST_URI=/en/users
in C:\OpenServer\domains\ybugs.local\protected\views\users\list.php (6)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (30)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (10)
2014/11/11 00:38:31 [error] [php] include(Translations.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\OpenServer\domains\ybugs.local\framework\YiiBase.php:427)
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\protected\views\users\list.php(6): spl_autoload_call()
#1 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(126): require()
#2 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(95): UsersController->renderInternal()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(869): UsersController->renderFile()
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(782): UsersController->renderPartial()
#5 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(30): UsersController->render()
#6 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(10): UsersController->actionList()
#7 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#8 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): UsersController->runAction()
#10 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): UsersController->runActionWithFilters()
#11 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): UsersController->run()
#12 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\ybugs.local\index.php(13): CWebApplication->run()
REQUEST_URI=/en/users
in C:\OpenServer\domains\ybugs.local\protected\views\users\list.php (6)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (30)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (10)
2014/11/11 00:44:24 [error] [php] include(Translations.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\OpenServer\domains\ybugs.local\framework\YiiBase.php:427)
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\protected\views\users\list.php(34): spl_autoload_call()
#1 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(126): require()
#2 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(95): UsersController->renderInternal()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(869): UsersController->renderFile()
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(782): UsersController->renderPartial()
#5 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(30): UsersController->render()
#6 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(10): UsersController->actionList()
#7 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#8 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): UsersController->runAction()
#10 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): UsersController->runActionWithFilters()
#11 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): UsersController->run()
#12 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\ybugs.local\index.php(13): CWebApplication->run()
REQUEST_URI=/en/users
in C:\OpenServer\domains\ybugs.local\protected\views\users\list.php (34)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (30)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (10)
2014/11/11 00:47:50 [error] [php] include(Translations.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\OpenServer\domains\ybugs.local\framework\YiiBase.php:427)
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\protected\models\forms\UserForm.php(35): spl_autoload_call()
#1 C:\OpenServer\domains\ybugs.local\framework\base\CModel.php(333): UserForm->attributeLabels()
#2 C:\OpenServer\domains\ybugs.local\framework\web\helpers\CHtml.php(1390): UserForm->getAttributeLabel()
#3 C:\OpenServer\domains\ybugs.local\framework\web\widgets\CActiveForm.php(582): activeLabel()
#4 C:\OpenServer\domains\ybugs.local\protected\views\users\add.php(8): CActiveForm->label()
#5 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(126): require()
#6 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(95): UsersController->renderInternal()
#7 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(869): UsersController->renderFile()
#8 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(782): UsersController->renderPartial()
#9 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(190): UsersController->render()
#10 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): UsersController->actionAdd()
#11 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): UsersController->runAction()
#13 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): UsersController->runActionWithFilters()
#14 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): UsersController->run()
#15 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\OpenServer\domains\ybugs.local\index.php(13): CWebApplication->run()
REQUEST_URI=/en/users/add
in C:\OpenServer\domains\ybugs.local\protected\models\forms\UserForm.php (35)
in C:\OpenServer\domains\ybugs.local\protected\views\users\add.php (8)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (190)
2014/11/11 01:00:16 [error] [php] include(Translations.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\OpenServer\domains\ybugs.local\framework\YiiBase.php:427)
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\protected\views\users\edit.php(16): spl_autoload_call()
#1 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(126): require()
#2 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(95): UsersController->renderInternal()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(869): UsersController->renderFile()
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(782): UsersController->renderPartial()
#5 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(147): UsersController->render()
#6 unknown(0): UsersController->actionEdit()
#7 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#8 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#9 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#10 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): UsersController->runAction()
#11 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): UsersController->runActionWithFilters()
#12 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): UsersController->run()
#13 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\ybugs.local\index.php(13): CWebApplication->run()
REQUEST_URI=/en/users/edit/3
in C:\OpenServer\domains\ybugs.local\protected\views\users\edit.php (16)
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (147)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 13:52:02 [warning] [application] Failed to set unsafe attribute "files" of "IssueForm".
in /Applications/AMPPS/www/ybugs.local/protected/controllers/IssuesController.php (63)
in /Applications/AMPPS/www/ybugs.local/index.php (13)
2014/11/11 14:02:51 [error] [exception.CException] exception 'CException' with message 'ExtUsers and its behaviors do not have a method or closure named "getRoles".' in /Applications/AMPPS/www/ybugs.local/framework/base/CComponent.php:266
Stack trace:
#0 /Applications/AMPPS/www/ybugs.local/framework/db/ar/CActiveRecord.php(227): CComponent->__call('getRoles', Array)
#1 /Applications/AMPPS/www/ybugs.local/protected/controllers/UsersController.php(167): CActiveRecord->__call('getRoles', Array)
#2 /Applications/AMPPS/www/ybugs.local/protected/controllers/UsersController.php(167): ExtUsers->getRoles()
#3 /Applications/AMPPS/www/ybugs.local/framework/web/actions/CInlineAction.php(49): UsersController->actionAdd()
#4 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#6 /Applications/AMPPS/www/ybugs.local/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(282): CController->run('add')
#8 /Applications/AMPPS/www/ybugs.local/framework/web/CWebApplication.php(141): CWebApplication->runController('users/add')
#9 /Applications/AMPPS/www/ybugs.local/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/AMPPS/www/ybugs.local/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/en/users/add
---
2014/11/11 18:59:34 [error] [exception.CException] exception 'CException' with message 'CActiveForm and its behaviors do not have a method or closure named "login".' in C:\OpenServer\domains\ybugs.local\framework\base\CComponent.php:266
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\protected\views\users\add_user.php(8): CComponent->__call('login', Array)
#1 C:\OpenServer\domains\ybugs.local\protected\views\users\add_user.php(8): CActiveForm->login(Object(UserForm), 'login', Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#3 C:\OpenServer\domains\ybugs.local\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(782): CController->renderPartial('add_user', Array, true)
#6 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(190): CController->render('add_user', Array)
#7 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): UsersController->actionAdd()
#8 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#12 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('users/add')
#13 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/en/users/add
HTTP_REFERER=http://ybugs.local/en/users/add
---
2014/11/11 19:31:50 [warning] [application] Failed to set unsafe attribute "currently_updating_user_id" of "Users".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (180)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 19:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/edit".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('user/edit')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/en/user/edit/
HTTP_REFERER=http://ybugs.local/en/users/edit/8
---
2014/11/11 19:38:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/edit".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('user/edit')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/en/user/edit/1
HTTP_REFERER=http://ybugs.local/en/users/edit/8
---
2014/11/11 20:09:35 [warning] [application] Failed to set unsafe attribute "password" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (116)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:09:35 [warning] [application] Failed to set unsafe attribute "password" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (116)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:20:39 [warning] [application] Failed to set unsafe attribute "password" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (110)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:22:28 [warning] [application] Failed to set unsafe attribute "password" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (110)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:22:37 [warning] [application] Failed to set unsafe attribute "password" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (110)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:23:31 [warning] [application] Failed to set unsafe attribute "password" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (110)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:23:31 [warning] [application] Failed to set unsafe attribute "currently_updating_user_id" of "Users".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (117)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:23:40 [warning] [application] Failed to set unsafe attribute "password" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (110)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:23:40 [warning] [application] Failed to set unsafe attribute "currently_updating_user_id" of "Users".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (117)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:24:27 [warning] [application] Failed to set unsafe attribute "password" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (110)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:24:27 [warning] [application] Failed to set unsafe attribute "currently_updating_user_id" of "Users".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (117)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:24:36 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.role" is not defined.' in C:\OpenServer\domains\ybugs.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\auth\CWebUser.php(146): CComponent->__get('role')
#1 C:\OpenServer\domains\ybugs.local\protected\controllers\MainController.php(12): CWebUser->__get('role')
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): MainController->actionIndex()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('index')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/index')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/en/main/index
HTTP_REFERER=http://ybugs.local/en/main/login
---
2014/11/11 20:25:42 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.role" is not defined.' in C:\OpenServer\domains\ybugs.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\auth\CWebUser.php(146): CComponent->__get('role')
#1 C:\OpenServer\domains\ybugs.local\protected\controllers\MainController.php(12): CWebUser->__get('role')
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): MainController->actionIndex()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('index')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/index')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/en/main/index
HTTP_REFERER=http://ybugs.local/en/main/login
---
2014/11/11 20:25:46 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.role" is not defined.' in C:\OpenServer\domains\ybugs.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\auth\CWebUser.php(146): CComponent->__get('role')
#1 C:\OpenServer\domains\ybugs.local\protected\controllers\MainController.php(12): CWebUser->__get('role')
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): MainController->actionIndex()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('index')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/index')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/en/main/index
---
2014/11/11 20:25:49 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.role" is not defined.' in C:\OpenServer\domains\ybugs.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\auth\CWebUser.php(146): CComponent->__get('role')
#1 C:\OpenServer\domains\ybugs.local\protected\controllers\MainController.php(12): CWebUser->__get('role')
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): MainController->actionIndex()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('index')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/index')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/en
HTTP_REFERER=http://ybugs.local/en/users/list
---
2014/11/11 20:25:50 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php:23
Stack trace:
#0 [internal function]: UsersController->actionList(NULL)
#1 C:\OpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('list')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('users/list')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/en/users/list
HTTP_REFERER=http://ybugs.local/en/users/edit/8
---
2014/11/11 20:25:53 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.role" is not defined.' in C:\OpenServer\domains\ybugs.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\auth\CWebUser.php(146): CComponent->__get('role')
#1 C:\OpenServer\domains\ybugs.local\protected\controllers\MainController.php(12): CWebUser->__get('role')
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): MainController->actionIndex()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('index')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/index')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/en
HTTP_REFERER=http://ybugs.local/en/users/list
---
2014/11/11 20:25:58 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.role" is not defined.' in C:\OpenServer\domains\ybugs.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\auth\CWebUser.php(146): CComponent->__get('role')
#1 C:\OpenServer\domains\ybugs.local\protected\controllers\MainController.php(12): CWebUser->__get('role')
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): MainController->actionIndex()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('index')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/index')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/en/main/index
---
2014/11/11 20:26:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "logiut".' in C:\OpenServer\domains\ybugs.local\framework\web\CController.php:483
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(270): CController->missingAction('logiut')
#1 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('logiut')
#2 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/logiut')
#3 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/en/main/logiut
---
2014/11/11 20:42:07 [warning] [application] Failed to set unsafe attribute "currently_updating_user_id" of "Users".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (175)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:45:31 [warning] [application] Failed to set unsafe attribute "currently_updating_user_id" of "Users".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (175)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:46:07 [warning] [application] Failed to set unsafe attribute "password" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (110)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:46:07 [warning] [application] Failed to set unsafe attribute "role" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (110)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:46:07 [warning] [application] Failed to set unsafe attribute "currently_updating_user_id" of "Users".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (117)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:46:17 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.role" is not defined.' in C:\OpenServer\domains\ybugs.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\auth\CWebUser.php(146): CComponent->__get('role')
#1 C:\OpenServer\domains\ybugs.local\protected\controllers\MainController.php(12): CWebUser->__get('role')
#2 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): MainController->actionIndex()
#3 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('index')
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/index')
#8 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/en/main/index
HTTP_REFERER=http://ybugs.local/en/main/login
---
2014/11/11 20:48:21 [warning] [application] Failed to set unsafe attribute "currently_updating_user_id" of "Users".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (175)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:48:41 [warning] [application] Failed to set unsafe attribute "password" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (110)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:49:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://ybugs.local/en/users/edit/10
---
2014/11/11 20:49:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/11 20:49:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/11 20:53:21 [warning] [application] Failed to set unsafe attribute "currently_updating_user_id" of "Users".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (175)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:53:50 [warning] [application] Failed to set unsafe attribute "password" of "UserForm".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (110)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/11 20:53:50 [warning] [application] Failed to set unsafe attribute "currently_updating_user_id" of "Users".
in C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php (117)
in C:\OpenServer\domains\ybugs.local\index.php (13)
2014/11/12 20:04:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/12 20:04:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/11/12 20:29:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/add".' in C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('user/add')
#1 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/en/user/add
HTTP_REFERER=http://ybugs.local/en/users
---
2014/11/12 20:47:10 [error] [exception.CException] exception 'CException' with message 'Property "ExtUsers.getAllUsers" is not defined.' in C:\OpenServer\domains\ybugs.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\ybugs.local\framework\db\ar\CActiveRecord.php(145): CComponent->__get('getAllUsers')
#1 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(28): CActiveRecord->__get('getAllUsers')
#2 C:\OpenServer\domains\ybugs.local\protected\controllers\UsersController.php(10): UsersController->actionList()
#3 C:\OpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#4 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\OpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('index')
#8 C:\OpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#9 C:\OpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\OpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/en/users
---
